storage: /verdaccio/storage
plugin: /verdaccio/plugin
web:
  title: mHub npm registry
auth:
  htpasswd:
    file: ./htpasswd
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  "**":
    access: $all
    publish: $all
    proxy: npmjs
middlewares:
  audit:
    enabled: true
logs:
  - { type: stdout, format: pretty, level: http }
